### ISSUE TITLE
Uploading account doesn't change unless I manually delete the youtube-bulk-upload-token.pickle

### ISSUE THREAD

**Issue by Judeisbad** [beveradb/youtube-bulk-upload#10] opened 2024-11-05 23:01 UTC
Even if I change the Client Secret File to upload to a different YouTube account, the program just checks the cached token instead of the updated secret file.

**Comment by beveradb** [comment] 2024-11-17 17:22
Feel free to submit a PR with a fix!
I don't have any personal motivation to work on this project but will merge PRs/release if others want to keep developing it :)

**Comment by beveradb** [comment] 2024-12-16 23:20
Closing this issue as I consider it a duplicate of #9

**Closed by beveradb** 2024-12-16 23:20 UTC
Labels: enhancement, help wanted

**Comment by beveradb** [comment] 2024-12-17 19:11
This should now be solved in version `0.5.1` with the new "Reset YouTube Auth" button (which just deletes the auth token created when you log in).

So, let's say you need to bulk upload some videos to one YouTube channel and then some other videos to a different channel, you can just click the button to reset your auth after the first set of videos are uploaded, and when you click `Run` again it'll open your browser to repeat the YouTube authentication flow, during which you can select a different channel.

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/3efd3033-eeca-4ca4-a75d-ffbfcaeb72be" />
